spring: 
    profiles: 
        active:
           - dev
---
server:
  port: 8001
  servlet:
    context-path: /provider

mybatis:
  type-aliases-package: com.hzit.api.entity

spring:
   profiles: dev
   application:
    name: springcloud-dept		#微服务最重要的是取名字！微服务对外暴露的名字
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/bj1901          # 数据库名称
    username: root
    password: root
logging:
  level:
    com.hzit.provider.mapper: debug

# eureka服务注册    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7004/eureka  # eureka注册中心的地址  表示将当前应用(springcloud-dept)注册到(eureka-server)
  instance:
    instance-id: springcloud-dept:8001   #修改别名
    prefer-ip-address: true 
    
# info信息  非必须   
info: 
 app.name:  springcloud-dept
 company.name:  www.hzitxx.com
 build.artifactId:  $project.artifactId$
 build.version:  $project.version$      
---
server:
  port: 8002
  servlet:
    context-path: /provider

mybatis:
  type-aliases-package: com.hzit.api.entity

spring:
   profiles: test
   application:
    name: springcloud-dept		#微服务最重要的是取名字！微服务对外暴露的名字
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/bj1901          # 数据库名称
    username: root
    password: root
logging:
  level:
    com.hzit.provider.mapper: debug

# eureka服务注册    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7005/eureka  # eureka注册中心的地址  表示将当前应用(springcloud-dept)注册到(eureka-server)
  instance:
    instance-id: springcloud-dept:8002   #修改别名
    prefer-ip-address: true 
    
# info信息  非必须   
info: 
 app.name:  springcloud-dept
 company.name:  www.hzitxx.com
 build.artifactId:  $project.artifactId$
 build.version:  $project.version$      